class Program
{
    public class NewsObj
    {
        public string NewsTitle { get; set; } = "";

        public string NewsDetails { get; set; } = "";

        public string NewsImage { get; set; } = "";

        public string StreetsNameNews { get; set; } = "";

        public DateOnly DataStart { get; set; }


    }
    public class Streets
    {
        public string Streets_name { get; set; } = "";
        public string City_name { get; set; } = "";
        public string ImagePath { get; set; } = "";


    }
    static void Main(string[] args)
    {
        //улицы 
        var users = new List<Streets>
        {
                new Streets {Streets_name="ул. Арбат", City_name="Москва", ImagePath="https://static.guidego.ru/611cfa7143a5ecb62f45ae20.1280x960.jpeg"},
                new Streets {Streets_name="ул. Невский проспект", City_name="Санкт-Петербург", ImagePath="https://interesnyefakty.org/wp-content/uploads/Nevskiy-prospekt.jpg"},
                new Streets { Streets_name = "ул. Красная площадь", City_name = "Москва", ImagePath = "https://kadet39.ru/wp-content/uploads/b/3/d/b3d095392697014794ff9bbe5fa514b1.jpeg" },
                new Streets { Streets_name = "пр. Ленина", City_name = "Новосибирск", ImagePath = "http://temples.ru/private/f001008/254_0276715b.jpg" },
                new Streets { Streets_name = "ул. Вайнера", City_name = "Екатеринбург", ImagePath = "https://pp.userapi.com/c631528/v631528618/458ba/ZrC2p3rNKt0.jpg" },
                new Streets { Streets_name = "ул. Тверская", City_name = "Москва", ImagePath = "https://img.1ku.ru/c81771d06501e988ca92146fab985ec5/wp-content/uploads/2018/09/91d23275e953e93cb60b63095b6881d2.jpg" },
                new Streets { Streets_name = "ул. Большая Садовая", City_name = "Санкт-Петербург", ImagePath = "https://img-fotki.yandex.ru/get/6310/66666794.4e/0_6c1d6_1d9ddd82_XXL.jpg" },
                new Streets { Streets_name = "ул. Красноармейская", City_name = "Новосибирск", ImagePath = "https://adresacafe.ru/wp-content/uploads/2020/01/common-10201.jpeg" },
                new Streets {Streets_name="ул. Лиговский проспект", City_name="Санкт-Петербург", ImagePath="https://webpulse.imgsmail.ru/imgpreview?mb=webpulse&key=pulse_cabinet-image-ec3b5777-ff2b-40ed-925b-883065c78bf7"},
                new Streets { Streets_name = "ул. 8 Марта", City_name = "Екатеринбург", ImagePath = "https://nesiditsa.ru/wp-content/uploads/2012/09/101.jpg" },


    };
        //новости
        var news = new List<NewsObj>
        {
                //new NewsObj { DataStart = new DateOnly (2023, 03 ,25),StreetsNameNews = "Ул. Ленина" ,NewsTitle = "Убили 5 негров в мерии", NewsDetails = "Комар типичный русский может летать на 100 метров, а отдельные виды летают на запах до 5 километров, что акула. Это значит, что для того, чтоб у вас не было комаров, комаров не должно быть в радиусе 100 метров.\r\nКомар плодится каждые 5 дней. Поэтому, если в сутки уничтожается менее 1/5 популяции комаров, то методы будут бесполезны.\r\nКомарам нужно много воды. Они живут возле заболоченых мест, либо там где вода. На участках они обычно вылетают вечером после жаркого дня, когда выпадает роса — чтоб напиться.", NewsImage = "https://cdn.botanichka.ru/wp-content/uploads/2021/02/15-interesnyih-faktov-o-komarah-kotoryie-vas-udivyat-01.jpg"},
                //new NewsObj { DataStart = new DateOnly (2023, 03 ,28),StreetsNameNews = "Ул. Ленина" ,NewsTitle = "Убили 5 комаров в мерии", NewsDetails = "Комар типичный русский может летать на 100 метров, а отдельные виды летают на запах до 5 километров, что акула. Это значит, что для того, чтоб у вас не было комаров, комаров не должно быть в радиусе 100 метров.\r\nКомар плодится каждые 5 дней. Поэтому, если в сутки уничтожается менее 1/5 популяции комаров, то методы будут бесполезны.\r\nКомарам нужно много воды. Они живут возле заболоченых мест, либо там где вода. На участках они обычно вылетают вечером после жаркого дня, когда выпадает роса — чтоб напиться.", NewsImage = "https://cdn.botanichka.ru/wp-content/uploads/2021/02/15-interesnyih-faktov-o-komarah-kotoryie-vas-udivyat-01.jpg"},
                //new NewsObj { DataStart = new DateOnly (2023, 03 ,27), StreetsNameNews = "Ул. Ленина", NewsTitle = "Спасли котёнка", NewsDetails = "С дерева спали котёнка. Спасителем оказался известный в своих кругах человек по прозвищу чёрный мечник Гатс — байронический герой. Он обладатель сильного и целеустремлённого характера. Смел, вплоть до безрассудства. Упрям. Уверен в себе. Прямолинеен, не терпит дипломатических тонкостей общения, предпочитая говорить прямо и по существу. Также весьма жесток и циничен. Общие черты характера сохраняются на протяжении всего повествования, но при этом характер Гатса очень сильно меняется в ходе сюжета.\r\n\r\nДо вступления в Отряд Сокола был замкнутым и неразговорчивым человеком, сторонившемся окружающих. В ходе службы в Отряде у него впервые появились друзья среди наёмников. Также он заработал репутацию безбашенного рубаки, коим он и являлся. Также он стал верным и преданным другом, готовым без раздумий помочь товарищам, даже ценой своей жизни.\r\n\r\nПосле Затмения характер Гатса сильно изменился. Он превратился в одинокого мстителя, желающего лишь отмщения, которое он творит своими руками, невзирая на цену и последствия. Он спокойно использует детей в качестве приманки, случайных свидетелей в качестве живого щита. Его абсолютно не волнуют последствия его действий для окружающих.\r\n\r\nПосле возрождения Гриффита характер Гатса снова начинает изменяться: Гатс-Мститель уступает место Гатсу-Защитнику. Хотя он всё также циничен, жесток и прямолинеен, но теперь его основная задача — защита Каски. Осознание этого меняет его характер. Теперь Гатс начинает задумываться о будущем и о последствиях своих действий, в первую очередь для Каски. Он принимает своих спутников, первоначально просто как помощников в путешествии, но затем к своему удивлению обретает в их лице новых друзей. Нынешний характер Гатса близок к его характеру в период службы в Отряде Сокола.", NewsImage = "https://yt3.googleusercontent.com/-7KyibSKtYr6KiFcVoqI6EoqgivLyN6fxTzancu7pvWg87aCFraHpRb_BNOjUgBGUXtEmmMG6g=s900-c-k-c0x00ffffff-no-rj"},
                //new NewsObj { DataStart = new DateOnly (2023, 03 ,28) ,StreetsNameNews = "Ул. Валеры" ,NewsTitle = "Найдена секта восхволяющая черепах", NewsDetails = "22.02.2023 недалеко от станции метро котельники была найдена секта с 100000000000 последователми", NewsImage = "https://kartinkin.net/uploads/posts/2022-03/1648185510_12-kartinkin-net-p-cherepashka-kartinki-14.jpg"},
                new NewsObj { DataStart = new DateOnly (2023, 03 ,25),StreetsNameNews = "ул. Арбат" ,NewsTitle = "Выставка архитектуры в Третьяковской галерее", NewsDetails = "В Третьяковской галерее с 1 апреля открыта выставка архитектуры, на которой представлены работы лауреатов международных премий. Выставка продлится до 31 мая.", NewsImage = "https://switki.ru/assets/i/ai/4/7/7/i/3285859.jpg"},
                new NewsObj { DataStart = new DateOnly (2023, 03 ,16),StreetsNameNews = "ул. Невский проспект" ,NewsTitle = "Новый магазин открыт на Невском проспекте", NewsDetails = "Сегодня на Невском проспекте открылся новый магазин, который предлагает широкий выбор товаров по доступным ценам.", NewsImage = "http://rasfokus.ru/images/photos/medium/9e406768105dd8a8779b3375c28a3ff2.jpg"},
                new NewsObj { DataStart = new DateOnly (2023, 02 ,27),StreetsNameNews = "ул. Красноармейская" ,NewsTitle = "Открытие музея на Красноармейской", NewsDetails = "Сегодня на Красноармйской открылся новый музей, где можно узнать о истории Москвы и России. Вход бесплатный.", NewsImage = "https://avatars.mds.yandex.net/get-altay/859900/2a0000015f8c36faf0e2ec034ae593ccdbde/XXL"},
                new NewsObj { DataStart = new DateOnly (2023, 01 ,08),StreetsNameNews = "пр. Ленина" ,NewsTitle = "Строительство новой высотки на пр. Ленина начнется в апреле", NewsDetails = "В апреле начнется строительство новой высотки на пр. Ленина. Здание будет иметь 60 этажей и станет одним из самых высоких в городе.", NewsImage = "https://sun9-31.userapi.com/impg/oHbj3dUxcskyv9EV5kXT5ku8kHHCSC5VHdQvFg/NpDdut40jxo.jpg?size=900x596&quality=95&sign=873d851c5f79999b2e60769aec630293&c_uniq_tag=DYVF1WVeZzpnAWwp1oIzwTn7HSgbofaSYC6mqr46wlg&type=album"},
                new NewsObj { DataStart = new DateOnly (2023, 03 ,29),StreetsNameNews = "ул. Вайнера" ,NewsTitle = "Открытие нового кафе на ул. Вайнера", NewsDetails = "Сегодня на ул. Вайнера открылось новое кафе, где можно попробовать вкусную еду и выпить свежесваренный кофе. Всех ждут с 10:00 до 22:00.", NewsImage = "https://kartarf.ru/images/heritage/1080/5/59189.jpg" },
                new NewsObj { DataStart = new DateOnly(2023, 04, 16), StreetsNameNews = "ул. Невский проспект", NewsTitle = "Открытие нового кафе на Невском проспекте", NewsDetails = "На Невском проспекте открылось новое кафе, предлагающее свежие и вкусные блюда по приятным ценам. Кафе расположено в самом центре города и является отличным местом для проведения встреч с друзьями и бизнес-партнерами.", NewsImage = "https://gcdn.tomesto.ru/img/place/000/022/580/restoran-mama-na-dache-na-nevskom-prospekte_c9f21_full-251119.jpg"},
                new NewsObj { DataStart = new DateOnly(2023, 02, 16), StreetsNameNews = "ул. Красная площадь", NewsTitle = "Международный фестиваль музыки на Красной площади", NewsDetails = "С 15 апреля на Красной площади пройдет международный фестиваль музыки, на котором выступят известные исполнители из разных стран мира. Фестиваль продлится до конца месяца и обещает быть ярким и запоминающимся событием для всех любителей музыки.", NewsImage = "https://catherineasquithgallery.com/uploads/posts/2021-02/1612905309_134-p-krasnaya-ploshchad-fon-173.jpg"},
                new NewsObj { DataStart = new DateOnly(2023, 01, 27), StreetsNameNews = "ул. Вайнера", NewsTitle = "Открытие нового магазина электроники на улице Вайнера", NewsDetails = "На улице Вайнера открылся новый магазин электроники, где можно приобрести самые современные и качественные гаджеты. В честь открытия магазин предлагает скидки на всю продукцию до конца месяца.", NewsImage = "http://photos.wikimapia.org/p/00/02/31/90/25_full.jpeg"},
                new NewsObj { DataStart = new DateOnly (2023, 03 ,07),StreetsNameNews = "ул. Лиговский проспект",NewsTitle = "Открытие нового кинотеатра", NewsDetails = "Сегодня на улице Лиговский проспект открылся новый кинотеатр «Киномакс Лиговский». В зале оборудованном по последнему слову техники, будут показывать самые новые и ожидаемые фильмы. ", NewsImage = "https://cre.ru/content/upload/players/object/normal/1517075969339.jpg"},
                new NewsObj { DataStart = new DateOnly (2023, 03 ,29),StreetsNameNews = "ул. 8 Марта",NewsTitle = "Открытие выставки живописи", NewsDetails = "Сегодня открылась выставка работ молодых художников в художественном центре на улице 8 Марта. Выставка будет проходить в течение месяца, на ней представлены работы разных жанров: пейзажи, портреты, натюрморты. ", NewsImage = "https://cdn.culture.ru/images/aab9ae0c-16b9-5d1c-a339-d99ea2265141"},
                new NewsObj { DataStart = new DateOnly(2023, 04, 06), StreetsNameNews = "ул. Красная площадь", NewsTitle = "Открытие выставки современного искусства в Государственном Историческом музее", NewsDetails = "С 1 апреля в Государственном Историческом музее открыта выставка современного искусства, на которой будут представлены работы известных современных художников. Выставка продлится до 31 мая.", NewsImage = "https://www.euromag.ru/storage/c/2021/07/01/1625153420_822314_31.jpg" },
                new NewsObj { DataStart = new DateOnly(2023, 04, 07), StreetsNameNews = "пр. Ленина", NewsTitle = "Открытие нового музея им. Ленина", NewsDetails = "Сегодня в Новосибирске открылся новый музей им. Ленина, который рассказывает о жизни и деятельности этого выдающегося политического деятеля. Музей представлен многочисленными экспонатами, включая оригинальные документы и фотографии. Вход свободный.", NewsImage = "http://www.uaio.ru/su/l24.jpg" },
                new NewsObj { DataStart = new DateOnly(2023, 02, 28), StreetsNameNews = "ул. Тверская", NewsTitle = "Выставка костюмов кино звезд в Музее кино", NewsDetails = "С 1 апреля в Музее кино открыта выставка костюмов, которые носили звезды кино в своих фильмах. На выставке можно увидеть костюмы таких знаменитостей, как Мэрилин Монро, Одри Хепберн, Кларк Гейбл и многие другие. Выставка продлится до 31 мая.", NewsImage = "https://user72557.clients-cdnnow.ru/wp-content/uploads/2019/02/converted_file_6cd3989f-1500x844.jpg" },
                new NewsObj {DataStart = new DateOnly(2023, 01, 15),StreetsNameNews = "ул. Вайнера",NewsTitle = "Открытие выставки \"Современное искусство\"",NewsDetails = "В галерее современного искусства на улице Вайнера с 15 апреля открылась новая выставка современного искусства. На выставке представлены произведения известных мировых художников и скульпторов.",NewsImage = "https://sinara-center.com/upload/iblock/88e/photo_5303394560648527008_y.jpg"},
                new NewsObj {DataStart = new DateOnly(2023, 02, 18),StreetsNameNews = "ул. Невский проспект",NewsTitle = "Концерт Симфонического оркестра в Мариинском театре",NewsDetails = "18 апреля в Мариинском театре на Невском проспекте состоится концерт Симфонического оркестра под управлением известного дирижера. В программе - произведения классической музыки известных композиторов.",NewsImage = "https://i.ytimg.com/vi/63PhLUsaoJA/maxresdefault.jpg"},
                new NewsObj {DataStart = new DateOnly(2023, 03, 21),StreetsNameNews = "ул. 8 Марта",NewsTitle = "Фестиваль цветов в Екатеринбурге",NewsDetails = "С 21 апреля в парке на улице 8 Марта в Екатеринбурге стартует фестиваль цветов. В рамках фестиваля пройдут мастер-классы по цветоводству, выставки флористики и конкурсы среди любителей садоводства.",NewsImage = "https://foxtime.ru/wp-content/uploads/2020/07/Zahod.jpg"},
                new NewsObj { DataStart = new DateOnly (2023, 04, 10), StreetsNameNews = "ул. Красная площадь", NewsTitle = "Открытие фонтанов на Красной площади", NewsDetails = "10 апреля на Красной площади в Москве состоится торжественное открытие фонтанов. Будут представлены новые конструкции и интересные водные шоу.", NewsImage = "https://static.mk.ru/upload/entities/2020/07/22/15/articles/facebookPicture/c3/70/e7/8f/8d2f1e7df25f18d16271cde84ef8d61c.jpg"},
                new NewsObj { DataStart = new DateOnly (2023, 04, 15), StreetsNameNews = "ул. Лиговский проспект", NewsTitle = "Концерт Лары Фабиан в Санкт-Петербурге", NewsDetails = "15 апреля на Лиговском проспекте в Санкт-Петербурге состоится концерт знаменитой певицы Лары Фабиан. Будут исполнены самые популярные хиты.", NewsImage = "https://news412media.com/wp-content/uploads/2022/02/4-19.jpg"},
                new NewsObj { DataStart = new DateOnly (2023, 01, 20), StreetsNameNews = "пр. Ленина", NewsTitle = "Открытие новой выставки в Новосибирске", NewsDetails = "20 апреля в Новосибирске на проспекте Ленина откроется новая выставка, посвященная искусству современности. Будут представлены работы молодых художников и скульпторов.", NewsImage = "https://www.oblgazeta.ru/media/filer_public/2023/03/28/bb333abe-5229-45ab-bd5d-3f535a8e4f6a-PAV_8419.jpg"},
                new NewsObj { DataStart = new DateOnly (2023, 01, 25), StreetsNameNews = "ул. Тверская", NewsTitle = "Открытие крупнейшей книжной ярмарки в Москве", NewsDetails = "С 25 апреля на улице Тверской в Москве откроется крупнейшая книжная ярмарка, на которой будут представлены лучшие произведения современной литературы, а также книги редких авторов.", NewsImage = "https://likes.ru/uploads/place/image/5688/super_medium_ac57843a76fa41a708cf63672e75d2e5.jpg"},
                new NewsObj {DataStart = new DateOnly(2023, 01, 03),StreetsNameNews = "пр. Ленина",NewsTitle = "Открытие новой выставки в Новосибирском музее",NewsDetails = "В Новосибирском музее им. В.Н. Сукачева 5 апреля открылась новая выставка, на которой будут представлены произведения современных художников. Выставка продлится до 15 мая.",NewsImage = "https://cdn4.telegram-cdn.org/file/rpx6l6Mu4o5_ktM_JUxQBG17WHgdChm_63mi9CSD8jnZ9ORKbr1eZD-zvgyrtjMu3iQmf2Vkmez6i5CSJGRYk6iFmbMjwFU_TLtuNUNrQ54Iax9SkFegbiHHr6fiW0XuXNY4hrlldr84CNY79NgayfSACFuy2qjdXjxnjr2dkqPMcKui2Zpr8RtTFAXEFGEBCf_3qs1lrakaiyiKV8mSVlZ1Pzv3C3sKnH3sQpgKCg6ZrmHAa3WlOTIsfbl9_xypdUawGBbAJMt4xj7E7ncUDeq9o5w3rz9jEumzawK7DjOqdBhym8eOZI9DNniNbPzrMcamfCNZNQz9RTqjjr4jLA.jpg"},
                new NewsObj {DataStart = new DateOnly(2023, 02, 10),StreetsNameNews = "ул. Вайнера",NewsTitle = "Открытие нового кафе в центре Екатеринбурга",NewsDetails = "В центре Екатеринбурга открылось новое кафе, в котором можно попробовать разнообразные блюда европейской кухни. Кафе работает ежедневно с 10:00 до 22:00.",NewsImage = "https://cdn.iportal.ru/news/2021/99/preview/a35c15f741192a2a529dc1af57d1d3720556e446_1280_720_c.jpg"},
                new NewsObj {DataStart = new DateOnly(2023, 04, 15),StreetsNameNews = "ул. Тверская",NewsTitle = "Открытие нового кинотеатра в центре Москвы",NewsDetails = "В центре Москвы открылся новый кинотеатр с технологией 4D, в котором зрители могут полностью погрузиться в происходящее на экране. Кинотеатр работает ежедневно с 10:00 до 23:00.",NewsImage = "https://img-fotki.yandex.ru/get/172684/29150237.59/0_bb15c_f2abe861_orig.jpg"},
                new NewsObj {DataStart = new DateOnly(2023, 04, 20),StreetsNameNews = "ул. Большая Садовая",NewsTitle = "Фестиваль джазовой музыки в Санкт-Петербурге",NewsDetails = "С 20 по 25 апреля в Санкт-Петербурге пройдет фестиваль джазовой музыки, на котором выступят известные музыканты из разных стран. Концерты будут проходить в различных концертных залах города.",NewsImage = "https://avatars.mds.yandex.net/i?id=2a000001871b0be0d0b7d41312e598255c5e-1356030-fast-images&n=13&exp=1"},
        };  
    }
}